version: "3"
services:
    npm:
      container_name: orbis-training-docker
      image: marlonric/orbis-training-docker:2.0.0
      ports:
        - "3030:3030"
        - "35729:35729"
      volumes:
        - ./:/app
      command: npm start
      working_dir: /app
    test:
      image: node:10.10.0-slim
      container_name: node-slim
      command: curl http://orbis-training-docker:1042
      working_dir: /app
      depends_on:
        - npm

networks:
  default:
    external:
      name: training